-- MySQL Script generated by MySQL Workbench
-- Sun Feb  6 19:03:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todolistdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todolistdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todolistdb` DEFAULT CHARACTER SET utf8 ;
USE `todolistdb` ;

-- -----------------------------------------------------
-- Table `todolistdb`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolistdb`.`user_roles` (
  `user_role_id` INT NOT NULL AUTO_INCREMENT,
  `user_role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_role_id`),
  UNIQUE INDEX `id_UNIQUE` (`user_role_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolistdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolistdb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_role_id` INT NOT NULL,
  `user_name` VARCHAR(40) NOT NULL,
  `user_login` VARCHAR(20) NOT NULL,
  `user_password` VARCHAR(20) NOT NULL,
  `user_email` VARCHAR(40) NOT NULL,
  `user_secret_qestion` VARCHAR(40) NOT NULL,
  `user_date_update` DATETIME(6) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `id_user_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_table_user_role_table1_idx` (`user_role_id` ASC) VISIBLE,
  UNIQUE INDEX `user_login_UNIQUE` (`user_login` ASC) VISIBLE,
  CONSTRAINT `fk_user_table_user_role_table1`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `todolistdb`.`user_roles` (`user_role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolistdb`.`results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolistdb`.`results` (
  `result_id` INT NOT NULL AUTO_INCREMENT,
  `result_creator_id` INT NOT NULL,
  `first_number` DOUBLE NOT NULL,
  `operator_type` VARCHAR(20) NOT NULL,
  `second_number` DOUBLE NOT NULL,
  `result_number` DOUBLE NOT NULL,
  `result_update_date` DATETIME(6) NULL,
  PRIMARY KEY (`result_id`),
  INDEX `fk_tasks_users1_idx` (`result_creator_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_users1`
    FOREIGN KEY (`result_creator_id`)
    REFERENCES `todolistdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
